### PR TITLE
Update add pre-requeriments README.md

### PR DESCRIPTION
**Pull request by EvertonMelo**
add Requeriments off install.

address Bounty NDI55N-OEHLZS-PNIZEU-L2XU7S-3477UZ-PBNZ5Q-5BPQ

( 3151 )

### CODE REVIEW

**Comment by EvertonMelo** [comment]
#1 about this

**Comment by cryptoBeliever** [comment]
@gimer could you confirm if java8 is necessary to compile this lib? 
Not sure how it solves #1. NemConfigurationPolicy is part of other lib or some configuration is missing?

**Comment by gimer** [comment]
are you kidding me?

**Comment by EvertonMelo** [comment]
@cryptoBeliever @gimer 

#1 User doubt, because the page has no requirements. 
#2 I added requirements.   


really a very professional posture.  @gimer  ?

ask him( @zhuyoulong ) if it was a joke: 


I start CommonStarter error as follows：

    I only start the main function directly
    Is not less NemConfigurationPolicy implementation class or in other modules?


org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.nem.deploy.NemConfigurationPolicy] is defined
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:371)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:331)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:968)
	at org.nem.deploy.CommonStarter.initializeConfigurationPolicy(CommonStarter.java:113)
	at org.nem.deploy.CommonStarter.boot(CommonStarter.java:200)
	at org.nem.deploy.CommonStarter.bootAndWait(CommonStarter.java:95)
	at org.nem.deploy.CommonStarter.main(CommonStarter.java:89)
 (org.nem.deploy.CommonStarter bootAndWait)
2018-02-14 09:42:56.804 信息 NEM 0.6.0-DEVELOPER BUILD shutdown... (org.nem.deploy.CommonStarter bootAndWait)


XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

really something open since Feb/2018 ( I would feel a lot of shame in your place. ) 

blame others for solving problems you do not see.

**Comment by gimer** [comment]
It is well known fact that NEM needs Java 8. Every release contains that information. Moreover if you're interested in getting the source directly you should be more then aware of the issue.

Demanding bounty for such thing is more than ridiculous.

**Comment by BloodyRookie** [comment]
Every release we make has clearly stated that it needs java 8.
To get a bounty it needs more than adding a few lines to the README.md.
Please apply for a bount only if you added anything substantial. We cannot give a bounty for such a small change.

**Pull request closed without merging**
